### ISSUE TITLE
Stream TODO list

### ISSUE THREAD

**Issue by noisy** [noisy/SpisTresci#3]
- [x] - fix problem with `restart always` local database
- [x] - setup jenkins
- [x] - introduce wait script for docker
- [ ] - ~~backup mechanism for DataStorageManager (based on BitBucket)~~
- [ ] - backup mechanism for all volumes (based Amazon S3)
- [ ] - setup sentry
- [x] - investigate/report bug with `"` around ENV values in `.env` file
- [ ] - VIRTUAL_HOST should be used to populate _Site_ in django admin
- [ ] - read about [ebay Commerce Network](https://publishers.ebaycommercenetwork.com/home.action?request_locale=en_GB) 
- [x] - incorrect log - "[Store:{}] There are no new revision available!"
